apiVersion: v1
kind: Pod
metadata:
  name: api-pod
spec:
  containers:
    - name: simple-api
      image: vtnorton/simple-node-api
      resources:
        requests:
          cpu: 100m
          memory: 128M
        limits:
          cpu: 250m
          memory: 256M
      ports:
        - containerPort: 27017